### ISSUE TITLE
v1.1.4 seems to have gone missing

### ISSUE THREAD

**Issue by jwalton** [addaleax/natives#2]
Not sure there's anything you can do about this (maybe publish a 1.1.5?) but:

https://github.com/npm/npm/issues/20766

**Comment by mvanderlee** [comment]
Not just 1.1.4. All versions are gone!

**Comment by dinozombie** [comment]
At least there's a funny error message.

`These are not the packages you are looking for. You can move along.`

**Comment by wheresvic** [comment]
Same issue here, cannot install gulp because it can't find any versions at all!

```
$ npm i natives
npm ERR! code E404
npm ERR! 404 Not Found: natives@latest

npm ERR! A complete log of this run can be found in:
```

**Comment by mvanderlee** [comment]
Probably related to: https://status.npmjs.org/incidents/t3j62lxb7jg3

**Comment by patr1ck** [comment]
My builds have also broken because of this. Also hey @victorparmar, we went to UWindsor together, what up

**Comment by ja5onkendall** [comment]
Any word on this getting resolved?

**Comment by mvanderlee** [comment]
It's working for me now.

**Comment by wheresvic** [comment]
@patr1ck haha what a small world! i just sent you a connection on linkedin let's catch up on there :)
